### ISSUE TITLE
Compatibility with Kiwiz invoice plugin

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/custom-order-numbers-woocommerce#33]
**Describe the bug**
The issue is with the Kiwiz Invoice plugin. The order number shown in the Invoice is different than the orde number shown after placing the order. 

**To Reproduce**
1) Install the Kiwiz plugin (https://www.kiwiz.io/extension-kiwiz-pour-woocommerce)
2) Enable the test mode under WooCommerce >> Settings >> Integration (https://prnt.sc/vlc5y8)
3) Keep the order number counter to Sequential.
4) Place an order.
5) Edit the order and click on the "Download Invoice" https://prnt.sc/vlcjhl.
6) You will see the order number different in the invoice and on the order page.

**Expected behavior**
The order number should be the same on the invoice and on the order page.

**Screenshots**
1) Orders page: https://prnt.sc/vlclt8
2) Attaching the invoice: 
[100000001.pdf](https://github.com/TycheSoftwares/custom-order-numbers-woocommerce-lite/files/5559174/100000001.pdf)

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/22721

**Comment by Shasvat7** [comment]
This issue doesn't need any code changes in our plugin. Changes need to be done in the KIWIZ Invoices Certification & PDF System plugin, hence closing the issue.

**Comment by apeksha10** [comment]
No need to check this issue as per @Shasvat7 comment.

Hence I have put an invalid label.
