### ISSUE TITLE
Custom Order Numbers for WooCommerce Paid version

### ISSUE THREAD

**Issue by ktchan1811** [TycheSoftwares/custom-order-numbers-woocommerce#34]
I have a issue on the above plugin, and also submit the report to Tyche Software. In my Wordpress dashboard show there is a Plugin to be updated but when when come to the Plugin dashboard shown nothing is to be updated. Which i guess is Phantom Plugin the I run a test and it showed that the Plugin is Custom Order Numbers is yet to update as shown in the attached.

![Image 25-11-2020 at 6 40 PM](https://user-images.githubusercontent.com/69572597/100302833-1ebad680-2fd6-11eb-95f7-4210b1a83342.jpg)

How do i go about it now? wait for the next update?
![Image 25-11-2020 at 6 40 PM](https://user-images.githubusercontent.com/69572597/100302940-575ab000-2fd6-11eb-949f-d8ed2d03471e.jpg)

**Comment by nidhinikulpatel** [comment]
Phantom plugin is no longer available for WordPress hence closing it.
