### ISSUE TITLE
New order number needs to be made available

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/custom-order-numbers-woocommerce#35]
**Describe the bug**
The client informed that the latest update has changed the hook used for generating the number. The problem is that the priority of the call is set to PHP_INT_MAX, which means that the nothing else can use the same woocommerce hook AND get the new order number.

Link: https://wordpress.org/support/topic/new-order-number-needs-to-be-made-available/

**Comment by apeksha10** [comment]
Discussed with @vishalck,

No need to test this issue as the client had confirmed it works fine for him.
