### ISSUE TITLE
The order number is missing, the woo_order page shows only prefix after the update.  

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/custom-order-numbers-woocommerce#47]
**Describe the bug**
The order number is missing, the woo_order page shows only prefix after the update.  

**To Reproduce**
1. When Order numbers counter set as Order ID. https://www.screencast.com/t/B2nesr1ECaU
2. Placed an order
3. Go to woo order page and I noticed that only prefix appear not custom order number
https://www.screencast.com/t/5X2uISaJ

**Expected behavior**
Woo order id should be displayed with the prefix 

2 clients have reported the same issue. 
https://tychesoftwares.freshdesk.com/a/tickets/27490
https://tychesoftwares.freshdesk.com/a/tickets/27496

**Comment by Shasvat7** [comment]
Another client reported this issue: https://tychesoftwares.freshdesk.com/a/tickets/27537
