### ISSUE TITLE
Search for Order Number is not Working

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/custom-order-numbers-woocommerce#52]
**Describe the bug**
What are the clients saying:

1. We are using WooCommerce version 5.1.0 and WordPress version 5.6.2. In the admin when searching by order number the older items do not appear. Items from the first few pages do. Could this be related to your plugin? I can’t turn it off for testing because it’s a high volume shop.

2. After running the database update, only new orders are searchable.
Using Version 1.3.1.

3. We were able to resolve this and regain the search function by downgrading to the Plugin Version 1.2.12 via the advanced view here:

https://wordpress.org/plugins/custom-order-numbers-for-woocommerce/advanced/

**The solution would be:**

The issue is coming due to the new meta which is not present in the old orders. To prevent this problem, we will be showing an admin notice to run a script so that the new meta key will be added in those orders where the new meta key is not present.

**Additional context**
https://wordpress.org/support/topic/search-for-order-number-not-working/

**Comment by Shasvat7** [comment]
The orders which were placed before installing the CON plugin will not have the meta keys present in them due to which while updating the database with the new meta key those orders were not updated and hence, this issue occurs.
