### ISSUE TITLE
Critical error message comes when we save the settings page

### ISSUE THREAD

**Issue by Shasvat7** [TycheSoftwares/custom-order-numbers-woocommerce#53]
**Describe the bug**
When we save the CON settings page, a critical error message comes of memory size exhausted.
This error comes because every time when we save the settings it updates the database base even though the prefix/suffix is not changed.

It should not update the database if the prefix/suffix is not been changed.

Note: This issue is not been replicated on our site.

**Expected behavior**
No error should come on saving the settings page.

https://wordpress.org/support/topic/search-for-order-number-not-working/

**Comment by apeksha10** [comment]
I am able to replicate the above issue. The critical error comes only when we have a large number of past orders.
On woo_apeksha, I have 21000 plus orders

Steps to replicate the above issue

1. Upload the latest git copy on woo_apeksha
2. Admin update notification received
3. Click on the update button
4. Go to the plugin setting page, try to change the prefix 
5. When I try to save that setting, the plugin throws me a critical error.

see the screenshot: https://www.screencast.com/t/TdzCNwr13M6e

Hence re-open this issue.

**Comment by apeksha10** [comment]
For the larger number of orders, I have raised another issue #60 

and For the above issue, I have followed the below steps

1. Take the latest git copy
2. Go to plugin setting page
3. Do not change the prefix and save the settings page
4. No Critical error message should appear?

Things are working fine. Hence I have closed this issue.
