### ISSUE TITLE
After updating the plugin, the site is getting crashed. 

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/custom-order-numbers-woocommerce#63]
**Describe the bug**
After updating your plugin Custom Order Numbers for Woocommerce we had a major database crash. Fortunately our host support managed to place back an older version and our webshop was accesable again after half an hour. We have been using your plugin for some time now and where very happy and satisfied. 

. FYI this is the culprit query that took done one of our shops:
SELECT SQL_CALC_FOUND_ROWS  wp_posts.* FROM wp_posts  LEFT JOIN wp_postmeta ON (wp_posts.ID = wp_postmeta.post_id AND wp_postmeta.meta_key = '_alg_wc_custom_order_number' )  LEFT JOIN wp_postmeta AS mt1 ON (wp_posts.ID = mt1.post_id AND mt1.meta_key = '_alg_wc_custom_order_number_meta_key_updated' ) WHERE 1=1  AND (
  wp_postmeta.post_id IS NULL
  AND
  mt1.post_id IS NULL
) AND wp_posts.post_type = 'shop_order' AND ((wp_posts.post_status <> 'trash' AND wp_posts.post_status <> 'auto-draft')) GROUP BY wp_posts.ID ORDER BY wp_posts.post_date DESC LIMIT 0, 5000

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/30738

**Comment by Chetna1510** [comment]
Another one has reported this: https://wordpress.org/support/topic/new-version-break-website/

**Comment by Chetna1510** [comment]
https://wordpress.org/support/topic/extremely-slow-admin-dashboard-since-update/

**Comment by apeksha10** [comment]
I took the latest git copy
Followed below steps 

1. Create new local
2. WC install and activated
3. Placed 5 to 6 orders
4. Install 1.3.2 , update admin notice
5. install the latest copy
6. old order are searchable
7. Add some prefix and Order numbers counter (random order number )
now, old and new orders are getting searched

Things are working fine. Hence I have put a fix label.
