### ISSUE TITLE
Orders are not getting tracked with custom prefix. 

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/custom-order-numbers-woocommerce#79]
**Describe the bug**
We are using prefix ORG- for our orders here, and a typical order looks like this: ORD-78271

And I can find such order on our admin, but not via order tracking: https://bestdealtoday.org/order-tracking/

On order tracking I find the tracking if I remove the prefix (leaving order ID)

**To Reproduce**

The issue is getting replicated on client's site only.
See the video: https://watch.screencastify.com/v/c2tSzJLNtm44kIKn8m0V

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/34890

**Comment by nidhinikulpatel** [comment]
The same is working fine with the default order tracking on the front end and client has added custom form on front end and didn't get back to us with the access hence closing it.
