### ISSUE TITLE
Renumerate Orders notice appear twice time. 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/custom-order-numbers-woocommerce#84]
**Describe the bug**
Renumerate Orders notice appears twice the time. 

**To Reproduce**
1. Go to woo-plugin setting page
2. Clicked on "Renumerate Orders tool" button 
3. Renumerate Orders notice appears twice the time. https://www.screencast.com/t/alGgEeJuHAoP

**Expected behavior**
Renumerate Orders notice should appear only one time

**Comment by nidhinikulpatel** [comment]
I am not able to replicate this issue see video here. https://www.screencast.com/t/OdL2o2y4

**Comment by apeksha10** [comment]
Still, I am able to see Renumerate Orders notice appear twice time


Hence re-open this issue

**Comment by nidhinikulpatel** [comment]
With latest copy I am not able to replicate this issue Hence closing it.
